version: 2

models:
  - name: olympic_all
    description: "Dimension table for athletes, containing unique athlete information."
    columns:
      - name: name
        description: "The full name of the athlete."
        tests:
          - not_null
      - name: sex
        description: "The gender of the athlete (M or F)."
        tests:
          - accepted_values:
              values: ['M', 'F']
              name: valid_sex_values
      - name: age
        description: "The age of the athlete at the time of the Olympics."
      - name: height_cm
        description: "The height of the athlete in centimeters."
      - name: weight_kg
        description: "The weight of the athlete in kilograms."
      - name: team
        description: "The team or country the athlete represents."
        tests:
          - not_null
      - name: noc
        description: "The National Olympic Committee 3-letter code representing the team."
        tests:
          - not_null
      - name: games
        description: "The Olympic Games the athlete participated in."
      - name: year
        description: "The year of the Olympics."
      - name: season
        description: "The season of the Olympics (Summer or Winter)."
      - name: city
        description: "The host city of the Olympics."
      - name: sport
        description: "The sport in which the athlete competes."
        tests:
          - not_null
      - name: event
        description: "The specific event in which the athlete competes."
        tests:
          - not_null
      - name: medal
        description: "The medal won by the athlete, if any."
        tests:
          - accepted_values:
              values: ['Gold', 'Silver', 'Bronze', 'No Medal']
              name: valid_medal_values
      - name: sex_index
        description: "Numeric index derived from the sex column for machine learning models."
      - name: season_index
        description: "Numeric index derived from the season column for machine learning models."
      - name: height_ft_in
        description: "The height of the athlete converted to feet and inches."
      - name: weight_lb
        description: "The weight of the athlete converted to pounds."


  - name: agg_athlete_medals
    description: "Aggregated table of medals won by athletes, partitioned by year and season, and clustered by noc and sport."
    columns:
      - name: year
        description: "The year of the Olympics."
        tests:
          - not_null
      - name: season
        description: "The season of the Olympics (Summer or Winter)."
        tests:
          - accepted_values:
              values: ['Summer', 'Winter']
      - name: noc
        description: "The National Olympic Committee 3-letter code."
        tests:
          - not_null
      - name: sport
        description: "The sport."
        tests:
          - not_null
      - name: medal_count
        description: "The count of medals won."
        tests:
          - not_null

  - name: olympic_all_partition_cluster
    description: "Aggregated table of athletes' information, partitioned by year and clustered by noc, season, and sport."
    config:
      materialized: 'table'
      partition_by:
        field: "year"
        data_type: "INT64"
      cluster_by:
        - 'noc'
        - 'season'
        - 'sport'
    columns:
      - name: name
        description: "The full name of the athlete."
        tests:
          - not_null
      - name: year
        description: "The year of the Olympics."
      - name: noc
        description: "The National Olympic Committee 3-letter code representing the team."
      - name: season
        description: "The season of the Olympics (Summer or Winter)."
      - name: sport
        description: "The sport in which the athlete competes."
      - name: height_ft_in
        description: "The height of the athlete converted to feet and inches."
      - name: weight_lb
        description: "The weight of the athlete converted to pounds."

