version: 2

models:
  - name: dim_athletes
    description: "Dimension table for athletes, containing unique athlete information."
    columns:
      - name: athlete_id
        description: "A unique identifier for each athlete, constructed from a combination of name and NOC."
        tests:
          - unique
          - not_null
      - name: name
        description: "The full name of the athlete."
      - name: sex
        description: "The gender of the athlete (M or F)."
      - name: age
        description: "The age of the athlete at the time of the Olympics."
      - name: height
        description: "The height of the athlete in centimeters."
      - name: weight
        description: "The weight of the athlete in kilograms."
      - name: team
        description: "The team or country the athlete represents."
      - name: noc
        description: "The National Olympic Committee 3-letter code representing the team."
      - name: sport
        description: "The sport in which the athlete competes."
      - name: event
        description: "The specific event in which the athlete competes."

  - name: fact_athlete_events
    description: "Fact table recording athlete performances in Olympic events."
    columns:
      - name: athlete_event_id
        description: "A unique identifier for each athlete's participation in an event, constructed from athlete_id and event details."
        tests:
          - unique
          - not_null
      - name: athlete_id
        description: "Reference to dim_athletes table."
        tests:
          - relationships:
              to: ref('dim_athletes')
              field: athlete_id
      - name: year
        description: "The year of the Olympics."
      - name: season
        description: "The season of the Olympics (Summer or Winter)."
      - name: city
        description: "The host city of the Olympics."
      - name: medal
        description: "The medal won by the athlete, if any."
      - name: sex_index
        description: "Numeric index derived from the sex column for machine learning models."
      - name: season_index
        description: "Numeric index derived from the season column for machine learning models."

  - name: agg_athlete_medals
    description: "Aggregated table of medals won by athletes, partitioned by year and season, and clustered by noc and sport."
    columns:
      - name: year
        description: "The year of the Olympics."
      - name: season
        description: "The season of the Olympics (Summer or Winter)."
      - name: noc
        description: "The National Olympic Committee 3-letter code."
      - name: sport
        description: "The sport."
      - name: medal_count
        description: "The count of medals won."
